# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1457116712);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1457116832);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1457116352);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1457116592);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1457116472);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1457116952);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 266240);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 34);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1457193004071");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1457194768071");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1457193005886");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1457196605886");
user_pref("browser.search.countryCode", "GB");
user_pref("browser.search.region", "GB");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160209234718");
user_pref("browser.slowStartup.averageTime", 4957);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20160209234718");
user_pref("browser.startup.homepage_override.mstone", "44.0.2");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1457202632360");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1457116298850");
user_pref("datareporting.policy.firstRunTime", "1457116232359");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.firstPaint", 4050);
user_pref("datareporting.sessions.current.main", 392);
user_pref("datareporting.sessions.current.sessionRestored", 4042);
user_pref("datareporting.sessions.current.startTime", "1457192982954");
user_pref("datareporting.sessions.current.totalTime", 15);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1457116230719,\"a\":195,\"t\":2498,\"c\":true,\"m\":272,\"fp\":8192,\"sr\":8136}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1457184497080,\"a\":14,\"t\":83,\"c\":false,\"m\":302,\"fp\":3259,\"sr\":3207}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"44.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"44.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:44.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1457116713);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160106.01");
user_pref("extensions.lastAppVersion", "44.0.2");
user_pref("extensions.lastPlatformVersion", "44.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455064670000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455064670000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455751106000,\"mt\":1455063905000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597111000}}}");
user_pref("font.internaluseonly.changed", false);
user_pref("gecko.buildID", "20160209234718");
user_pref("gecko.mstone", "44.0.2");
user_pref("gfx.crash-guard.glcontext.appVersion", "44.0.2");
user_pref("gfx.crash-guard.glcontext.deviceID", "Mesa DRI Intel(R) Haswell x86/MMX/SSE2");
user_pref("gfx.crash-guard.glcontext.driverVersion", "3.0 Mesa 11.0.2");
user_pref("gfx.crash-guard.status.glcontext", 1);
user_pref("idle.lastDailyNotification", 1457117190);
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1457116300);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20160209234718");
user_pref("media.gmp-manager.lastCheck", 1457116299);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1457117191);
user_pref("places.history.expiration.transient_current_max_pages", 24479);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1457117190);
user_pref("toolkit.startup.last_success", 1457192983);
user_pref("toolkit.telemetry.cachedClientID", "2737c371-a136-4cc0-b994-58b4cb3d942d");
user_pref("toolkit.telemetry.previousBuildID", "20160209234718");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
